name: "Hello World"
description: "Greet someone and record the time"
inputs:
  app-name:
    required: true
  tag-key-color:
    required: true
  tag-key-evn:
    required: false
  env-target:
    required: false
  aws-access-key-id:
    required: true
  aws-secret-access-key:
    required: true
  region:
    required: true
outputs:
  source-env-name:
    description: "Name of the source environment"
  dest-env-name:
    description: "Name of the destination environment"
runs:
  using: "node12"
  main: "index.js"
