name: "AWS Elastic Beanstalk blue green deploy"
inputs:
  action:
    required: true
  env-name:
    required: false
  app-name:
    required: false
  tag-key-color:
    required: false
  tag-key-env:
    required: false
  env-target:
    required: false
  aws-access-key-id:
    required: true
  aws-secret-access-key:
    required: true
  region:
    required: true
outputs:
  source-env-name:
    description: "Name of the source environment"
  dest-env-name:
    description: "Name of the destination environment"
runs:
  using: "node12"
  main: "dist/index.js"
